config/routes.rb
Rails.application.routes.draw do
  
resources :images
get 'probar', to: 'control#saludo' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader
    
    validates  :description ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
def saludo
@nombre = 2 * 5
end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    
    before_action :set_image, only: [:show, :edit, :update,:destroy]
    
    def index
        @images = Image.all
    end
    
    def  new
          
        @image = Image.new
    
    end
    
    
    def create
    #render plain: params[:image].inspect
        @image=Image.new image_params
       if @image.save
         return redirect_to image_path
       end

       render :new
    end

    
    def show
        
    end

    def edit
        
    end
    
    def update
        
        @image.update  image_params
        redirect_to @image
    end
    
    def destroy
        
        @image.destroy
        redirect_to images_path
    end
    
    private
    def image_params
        params.require(:image).permit(:description, :picture) 
        
    end
   
    def set_image
        @image = Image.find params[:id]
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/control/saludo.html.erb
<p>controlador: <%= @nombre %></p>

app/views/images/_form.html.erb
<%- if @image.errors.any? %>
    <div class="alert alert-danger">
        <div class="alert heading">Ooops</div>
        <h3>Ha ocurrido un error</h3>
    </div>
<%end%>  

<div class="container">
    <div class="form-group">
        <%=form_for @image do |f| %>
        <%=f.label :descripcion %>
        <%=f.text_field :description,  class:'form-control'%>
        <%- if @image.errors.any? %>
        <span class="badge badge-pill badge-danger">
            <%= @image.errors[:description].first %>
        </span>
        <%end%>

        
        <br>
        <%=f.label :descripcion %>
        <%=f.file_field :picture %>


        <%=f.submit 'Enviar', :class=> 'btn btn-primary' %> 
        <%end%>
    </div>
</div>

app/views/images/_image.html.erb
<div class="col-4">
    
        <div class="row">
            <figure class="figure">
               
                <%= image_tag  image.picture.medium.url,class: "figure-img img-fluid rounded" %>    
                <!-- <img src="https://i.pinimg.com/236x/31/0e/bc/310ebc289269447e9801802827ef2102--cigarette-holder-cigarette-case.jpg" class="figure-img img-fluid rounded" alt=""> -->
                
                <figcaption class="figure-caption">
                    <%= image.description %>
                    <%= link_to 'Edit', edit_image_path(image) %>
                    <%= link_to 'Destroy', image,  method: :delete, data: {confirm: 'sure'} %>
                </figcaption>
                
            </figure>
        
        </div>
    
</div>

app/views/images/edit.html.erb
<div class="container">
<h1>Editar</h1>
<%= render 'form'  %>
</div>

app/views/images/index.html.erb
<div class="container">
    <div class="row">
        <%= render @images %>        
    </div>
</div>

app/views/images/new.html.erb
<div class="container">
    <p>hola desde vista| method:create</p>

    <%= render 'form' %>
</div>

app/views/images/show.html.erb
<%= image_tag  @image.picture.thumb.url,class: "figure-img img-fluid rounded" %>
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>